module.exports.descriptors = [
    'Joshua Tree',
    'Dark Sky',
    'Pine Forest',
    'Ashwood Forest',
    'Acadia Rim',
    'Arches',
    'Big Bend',
    'Cherry Springs',
    'Big Cypress',
    'Canyonlands',
    'Shady Reef',
    'Crater Lake',
    'Glacier',
    'Red Basin',
    'Bryce Canyon',
    'Gomi Volcanic',
    'Sequoia Mount',
    'White Sand',
    'White Dunes',
    'Red Mountain',
    'Citrus Groves',
    'Red Oak',
    'White Pine',
    'Maple Groves',
    'Blue Glacier',
    'Newhaven',
    'Harbury Heath',
    'Eastport Lake',
    'Oxhampton',
    'Oakwood',
    'Birchwood',
    'Washburn',
    'Woodbury',
    'Diamond Lake',
    'Elmwood',
    'Cedar Archs',
    'Rosemount',
    'Bryant Lake',
    'Prior Lake',
    'Elm Creek',
    'Somerset',
    'Devon',
    'Norwood Hill',
    'Weston Hill',
    'Millbury',
    'Concordia',
    'Aspen Hill',
    'Cedar Lake',
    'Cherry Creek',
    'Palmer Creek'
];



module.exports.places = [
    'National Park',
    'Preserve',
    'State Park',
    'Reserve',
    'Sky Reserve',
    'National Reserve',
    'Park',
    'Observatory',
    'Natural Center'
];
